/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.5.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("java")
    id("war")
}

repositories {
    mavenCentral()
}

// set war name to ROOT
tasks.war {
  archiveFileName.set("ROOT.war")
}


// add postgres jdbc
dependencies {
    // implementation("org.postgresql:postgresql:42.2.23")

    // jakarta servlet api
    compileOnly("jakarta.servlet:jakarta.servlet-api:5.0.0")
    // jakarta persistence api
    // compileOnly("jakarta.persistence:jakarta.persistence-api:3.0.0")
}
