services:
  wildfly:
    image: quay.io/wildfly/wildfly:27.0.0.Final-jdk17 
    ports:
      - "80:8080"
      - "9990:9990"
    volumes:
      - "./build/libs/ROOT.war:/opt/jboss/wildfly/standalone/deployments/ROOT.war"
